# Generated by Django 6.0.1 on 2026-06-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0002_alter_senarecord_dateofappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='senarecord',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
