# Generated by Django 6.0.1 on 2026-06-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0004_fix_datetimefield_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senarecord',
            name='dateOfAppointment',
            field=models.DateField(),
        ),
    ]
