# Generated by Django 6.0.1 on 2026-06-19 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0008_remove_senarecord_incharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClient',
            fields=[
                ('emailClient_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_emailClient',
            },
        ),
        migrations.CreateModel(
            name='EmailRespondent',
            fields=[
                ('emailRespondent_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_emailRespondent',
            },
        ),
        migrations.CreateModel(
            name='SenaMinutes',
            fields=[
                ('minute_id', models.AutoField(primary_key=True, serialize=False)),
                ('minuteTitle', models.CharField(max_length=255)),
                ('minuteFile', models.FileField(blank=True, null=True, upload_to='minutes/')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_senaMinutes',
            },
        ),
        migrations.RemoveField(
            model_name='senarecord',
            name='clientEmail',
        ),
        migrations.RemoveField(
            model_name='senarecord',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='senarecord',
            name='senaStatus',
        ),
        migrations.RemoveField(
            model_name='senarecord',
            name='start_time',
        ),
        migrations.AddField(
            model_name='senarecord',
            name='clientStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('dismissed', 'Dismissed'), ('lack_of_interest', 'Lack of Interest'), ('nlrc', 'NLRC'), ('ongoing', 'On Going'), ('settled', 'Settled'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='respondentStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('dismissed', 'Dismissed'), ('lack_of_interest', 'Lack of Interest'), ('nlrc', 'NLRC'), ('ongoing', 'On Going'), ('settled', 'Settled'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AgencyRecord',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('agencyName', models.CharField(max_length=255)),
                ('agencyDescription', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('sena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_records', to='sena.senarecord')),
            ],
            options={
                'db_table': 'tbl_agencyRecord',
            },
        ),
        migrations.AddField(
            model_name='senarecord',
            name='emailClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sena_records', to='sena.emailclient'),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='emailRespondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sena_records', to='sena.emailrespondent'),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='minute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sena_records', to='sena.senaminutes'),
        ),
    ]
