# Generated by Django 6.0.1 on 2026-06-19 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0009_emailclient_emailrespondent_senaminutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenaAppointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('dateOfAppointment', models.DateField()),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_senaAppointment',
            },
        ),
        migrations.RemoveField(
            model_name='senarecord',
            name='dateOfAppointment',
        ),
        migrations.AddField(
            model_name='senarecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sena_records', to='sena.senaappointment'),
        ),
    ]
