# Generated by Django 6.0.1 on 2026-06-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0010_senaappointment_remove_senarecord_dateofappointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senarecord',
            name='emailClient',
        ),
        migrations.RemoveField(
            model_name='senarecord',
            name='emailRespondent',
        ),
        migrations.AddField(
            model_name='senarecord',
            name='emailClients',
            field=models.ManyToManyField(blank=True, related_name='sena_records_clients', to='sena.emailclient'),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='emailRespondents',
            field=models.ManyToManyField(blank=True, related_name='sena_records_respondents', to='sena.emailrespondent'),
        ),
    ]
