# Generated by Django 6.0.1 on 2026-06-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0011_remove_senarecord_emailclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senarecord',
            name='appointment',
        ),
        migrations.AddField(
            model_name='senarecord',
            name='appointments',
            field=models.ManyToManyField(blank=True, related_name='sena_records', to='sena.senaappointment'),
        ),
    ]
