# Generated by Django 6.0.1 on 2026-06-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0012_remove_senarecord_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senarecord',
            name='clientStatus',
            field=models.CharField(choices=[('scheduled', 'SCHEDULED'), ('drop_due_to_absences', 'DROP DUE TO ABSENCES'), ('drop_due_to_lack_of_interest', 'DROP DUE TO LACK OF INTEREST'), ('endorse_to_adjudicator', 'ENDORSE TO ADJUDICATOR'), ('nlrc', 'NLRC'), ('ongoing', 'ONGOING'), ('settled', 'SETTLED'), ('withdrawn', 'WITHDRAWN')], default='scheduled', max_length=35),
        ),
        migrations.AlterField(
            model_name='senarecord',
            name='respondentStatus',
            field=models.CharField(choices=[('scheduled', 'SCHEDULED'), ('drop_due_to_absences', 'DROP DUE TO ABSENCES'), ('drop_due_to_lack_of_interest', 'DROP DUE TO LACK OF INTEREST'), ('endorse_to_adjudicator', 'ENDORSE TO ADJUDICATOR'), ('nlrc', 'NLRC'), ('ongoing', 'ONGOING'), ('settled', 'SETTLED'), ('withdrawn', 'WITHDRAWN')], default='scheduled', max_length=35),
        ),
    ]
