# Generated by Django 6.0.1 on 2026-06-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0013_alter_senarecord_clientstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyrecord',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
