# Generated by Django 6.0.1 on 2026-06-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0014_agencyrecord_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='senarecord',
            name='clientBase',
            field=models.CharField(blank=True, choices=[('landbased', 'Landbased'), ('seabased', 'Seabased')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='clientDeployed',
            field=models.CharField(blank=True, choices=[('deployed', 'Deployed'), ('non_deployed', 'Non-Deployed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='clientGender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='clientIndigency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='clientPWD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='clientParent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='seadNumber',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='senaPurpose',
            field=models.CharField(blank=True, choices=[('recruitment_violation', 'Recruitment Violation'), ('money_claims', 'Money Claims'), ('daw', 'DAW'), ('dae', 'DAE'), ('rv_mc', 'RV/MC')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='senarecord',
            name='settledDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
