# Generated by Django 6.0.1 on 2026-06-19 05:21

from django.db import migrations


def remove_duplicate_agencies(apps, schema_editor):
    """Remove duplicate agency records, keeping the first one"""
    AgencyRecord = apps.get_model('sena', 'AgencyRecord')
    
    # Get all agency names that appear more than once
    from django.db.models import Count
    duplicates = AgencyRecord.objects.values('agencyName').annotate(count=Count('agency_id')).filter(count__gt=1)
    
    for dup in duplicates:
        agency_name = dup['agencyName']
        # Get all records with this name, ordered by ID so we keep the first one
        all_records = AgencyRecord.objects.filter(agencyName=agency_name).order_by('agency_id')
        # Delete all except the first one
        for record in all_records[1:]:
            record.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0015_senarecord_clientbase_senarecord_clientdeployed_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_agencies),
    ]
