# Generated by Django 6.0.1 on 2026-06-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0016_remove_duplicate_agencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyrecord',
            name='agencyName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
