# Generated by Django 6.0.1 on 2026-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0017_unique_agency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyrecord',
            name='agencyName',
            field=models.CharField(max_length=255),
        ),
    ]
